# 语言配置文件
# 统一管理所有语言相关的配置

# 支持的语言列表
languages:
  zh:
    name: "中文"
    code: "zh"
    enabled: true
    is_source: true
    is_target: true
  
  en:
    name: "英语"
    code: "en"
    enabled: true
    is_source: true
    is_target: true
    endpoint_name: "english"
  
  th:
    name: "泰语"
    code: "th"
    enabled: true
    is_source: false
    is_target: true
    endpoint_name: "thai"
  
  vie:
    name: "越南语"
    code: "vie"
    enabled: true
    is_source: false
    is_target: true
    endpoint_name: "vietnamese"
  
  id:
    name: "印尼语"
    code: "id"
    enabled: true
    is_source: false
    is_target: true
    endpoint_name: "indonesian"
  
  may:
    name: "马来语"
    code: "may"
    enabled: true
    is_source: false
    is_target: true
    endpoint_name: "malay"
  
  fil:
    name: "菲律宾语"
    code: "fil"
    enabled: true
    is_source: false
    is_target: true
    endpoint_name: "filipino"
  
  bur:
    name: "缅甸语"
    code: "bur"
    enabled: true
    is_source: false
    is_target: true
    endpoint_name: "burmese"
  
  hkm:
    name: "高棉语"
    code: "hkm"
    enabled: true
    is_source: false
    is_target: true
    endpoint_name: "khmer"
  
  lao:
    name: "老挝语"
    code: "lao"
    enabled: true
    is_source: false
    is_target: true
    endpoint_name: "lao"
  
  tam:
    name: "泰米尔语"
    code: "tam"
    enabled: true
    is_source: false
    is_target: true
    endpoint_name: "tamil"
  
  auto:
    name: "自动检测"
    code: "auto"
    enabled: true
    is_source: true
    is_target: false

# 单一目标语言接口配置
single_target_endpoints:
  - code: "en"
    endpoint: "translate_to_english"
    description: "翻译到英语"
    from_lang: "zh"
  
  - code: "th"
    endpoint: "translate_to_thai"
    description: "翻译到泰语"
    from_lang: "zh"
  
  - code: "vie"
    endpoint: "translate_to_vietnamese"
    description: "翻译到越南语"
    from_lang: "zh"
  
  - code: "id"
    endpoint: "translate_to_indonesian"
    description: "翻译到印尼语"
    from_lang: "zh"
  
  - code: "may"
    endpoint: "translate_to_malay"
    description: "翻译到马来语"
    from_lang: "zh"
  
  - code: "fil"
    endpoint: "translate_to_filipino"
    description: "翻译到菲律宾语"
    from_lang: "zh"
  
  - code: "bur"
    endpoint: "translate_to_burmese"
    description: "翻译到缅甸语"
    from_lang: "zh"
  
  - code: "hkm"
    endpoint: "translate_to_khmer"
    description: "翻译到高棉语"
    from_lang: "zh"
  
  - code: "lao"
    endpoint: "translate_to_lao"
    description: "翻译到老挝语"
    from_lang: "zh"
  
  - code: "tam"
    endpoint: "translate_to_tamil"
    description: "翻译到泰米尔语"
    from_lang: "zh"

# 前端配置
frontend:
  # 语言选择器选项
  source_languages:
    - code: "auto"
      name: "自动检测"
    - code: "zh"
      name: "中文"
    - code: "en"
      name: "英语"
  
  target_languages:
    - code: "zh"
      name: "中文"
    - code: "en"
      name: "英语"
    - code: "th"
      name: "泰语"
    - code: "vie"
      name: "越南语"
    - code: "id"
      name: "印尼语"
    - code: "may"
      name: "马来语"
    - code: "fil"
      name: "菲律宾语"
    - code: "bur"
      name: "缅甸语"
    - code: "hkm"
      name: "高棉语"
    - code: "lao"
      name: "老挝语"
    - code: "tam"
      name: "泰米尔语"

# 测试配置
testing:
  # 测试用的语言代码列表
  target_languages: ["en", "th", "vie", "id", "may", "fil", "bur", "hkm", "lao", "tam"]
  
  # 测试文本
  test_texts:
    zh: ["你好世界", "早上好", "谢谢", "再见", "欢迎"]
    en: ["Hello World", "Good morning", "Thank you", "Goodbye", "Welcome"]
    simple: ["测试", "API", "翻译"]
